### ISSUE TITLE
Low performance when handling request in framed mode.

### ISSUE THREAD

**Issue by alishir** [actix/actix-http#6]
Hi, 
I do simple performance test against `hello-world` example that uses `h1::H1Service` and `framed_hello` example that send response directly on a frame. 
The command that I used for performance test is `wrk -t8 -c4000 -d5s http://127.0.0.1:8080/`. When using `h1::H1Service` the result is about `29000` request per second while when using frames directly the result is about only `200` request per second. I think using frames directly should gain better results, would you please explain to me where should I change to get better performance when using frames directly?

**Comment by fafhrd91** [comment]
I guess this is connection keep-alive. Try to disable keep alive for h1service

**Comment by alishir** [comment]
h1service handles 29000 request per second, but using framed without h1service only handles 200 request per second, it seems there is some problem in sample code that implemented in frame. Here is the code block of framed example:
```rust
// This code handle only 200 request per second!!!!
fn main() {
    env::set_var("RUST_LOG", "framed_hello=info");
    env_logger::init();

    Server::new().bind("framed_hello", "127.0.0.1:8080", || {
        IntoFramed::new(|| h1::Codec::new(ServiceConfig::default()))
            .and_then(TakeItem::new().map_err(|_| ()))
            .and_then(|(_req, _framed): (_, Framed<_, _>)| {
                SendResponse::send(_framed, Response::Ok().body("Hello world!"))
                    .map_err(|_| ())
                    .map(|_| ())
            })
    }).unwrap().run();
}
```

And here is the code block of h1service example:
```rust
// This code handle about 29000 request per second
fn main() {
    env::set_var("RUST_LOG", "hello_world=info");
    env_logger::init();

    Server::new().bind("hello-world", "127.0.0.1:8080", || {
        h1::H1Service::build()
            .client_timeout(1000)
            .client_disconnect(1000)
            .server_hostname("localhost")
            .finish(|_req| {
                info!("{:?}", _req);
                let mut res = Response::Ok();
                res.header("x-head", HeaderValue::from_static("dummy value!"));
                future::ok::<_, ()>(res.body("Hello world!"))
            })
            .map(|_| ())
    }).unwrap().run();
}

```

**Comment by fafhrd91** [comment]
Framed example drops connection after sending response. H1service does not

**Comment by alishir** [comment]
Would you please guide me how should I implement that?

**Comment by fafhrd91** [comment]
Here is full implementation https://github.com/fafhrd91/actix-http/blob/master/src/h1/dispatcher.rs#L39

**Comment by alishir** [comment]
Thanks a lot :-)

**Comment by fafhrd91** [comment]
h1::Dispatcher is designed for application. You may want to tune your dispatcher specifically for proxy use case. It could be separate crate within actix org
